server:
  port: 8762
spring:
  application:
    name: config-server
  profiles:
      active: native
  cloud:
    config:
      server:
        native: #配置文件在本地
          search-locations: classpath:${config-location}
      fail-fast: true #快速失败策略
        #git: #配置文件在远程的git仓库
        #  uri:
        #  username:
        #  password:

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://admin:123@localhost:8761/eureka/

#actuator设置
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点,默认是info和health
  endpoint:
    health:
      show-details: always #默认是never
